name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort pytest pytest-cov build
        pip install -e .
    - name: Lint with flake8
      run: |
        flake8 turknlp
    - name: Format check
      run: |
        black --check turknlp
        isort --check-only turknlp
    - name: Test with pytest
      run: |
        pytest --cov=turknlp
    - name: Build package
      run: |
        python -m build
